//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUSKF.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AUSKF.Domain.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSKFID.
        /// </summary>
        public static string AuskfId {
            get {
                return ResourceManager.GetString("AuskfId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the directory {0}.
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public display name.
        /// </summary>
        public static string DisplayAttributeDisplayName {
            get {
                return ResourceManager.GetString("DisplayAttributeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        public static string DisplayAttributeEmailAddress {
            get {
                return ResourceManager.GetString("DisplayAttributeEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to karma.
        /// </summary>
        public static string DisplayAttributeKarma {
            get {
                return ResourceManager.GetString("DisplayAttributeKarma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string DisplayAttributePassword {
            get {
                return ResourceManager.GetString("DisplayAttributePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagline.
        /// </summary>
        public static string DisplayAttributeTagline {
            get {
                return ResourceManager.GetString("DisplayAttributeTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        public static string DisplayAttributeTopicTitle {
            get {
                return ResourceManager.GetString("DisplayAttributeTopicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name.
        /// </summary>
        public static string DisplayAttributeUserName {
            get {
                return ResourceManager.GetString("DisplayAttributeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dojo Listings.
        /// </summary>
        public static string DojoListings {
            get {
                return ResourceManager.GetString("DojoListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Dues Policy.
        /// </summary>
        public static string Dues {
            get {
                return ResourceManager.GetString("Dues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please supply a password.
        /// </summary>
        public static string ErrorMessagePassword {
            get {
                return ResourceManager.GetString("ErrorMessagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user name is required.
        /// </summary>
        public static string ErrorMessageUserName {
            get {
                return ResourceManager.GetString("ErrorMessageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ExternalLoginConfirmationViewModel_Email_Email {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationViewModel_Email_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ExternalLoginConfirmationViewModel_Password_Password {
            get {
                return ResourceManager.GetString("ExternalLoginConfirmationViewModel_Password_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed validation.
        ///.
        /// </summary>
        public static string FailedValidation {
            get {
                return ResourceManager.GetString("FailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federation Listings.
        /// </summary>
        public static string FederationListings {
            get {
                return ResourceManager.GetString("FederationListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found. (404).
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Disclaimer: This website is posted as a service to the All United States Kendo Federation. Information on this website is posted from many different sources and every effort is made to post accurate information. Errors may occur and users use this site without warranties of any sort implied and at their own risk.&apos;.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group color.
        /// </summary>
        public static string GroupColor {
            get {
                return ResourceManager.GetString("GroupColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description.
        /// </summary>
        public static string GroupDescription {
            get {
                return ResourceManager.GetString("GroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group receive private messages.
        /// </summary>
        public static string GroupReceivePrivateMessages {
            get {
                return ResourceManager.GetString("GroupReceivePrivateMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted reference to HttpContext.Current which was null..
        /// </summary>
        public static string HttpContextNull {
            get {
                return ResourceManager.GetString("HttpContextNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All United States Kendo Federation.
        /// </summary>
        public static string KendoFederation {
            get {
                return ResourceManager.GetString("KendoFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability Release Form.
        /// </summary>
        public static string Liability {
            get {
                return ResourceManager.GetString("Liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSKF.
        /// </summary>
        public static string NameHeaderText {
            get {
                return ResourceManager.GetString("NameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News and Events.
        /// </summary>
        public static string NewsEvents {
            get {
                return ResourceManager.GetString("NewsEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSKF Newsletters.
        /// </summary>
        public static string NewsLetters {
            get {
                return ResourceManager.GetString("NewsLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officers and Board Members.
        /// </summary>
        public static string Officers {
            get {
                return ResourceManager.GetString("Officers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// This method is a member of {0}..
        /// </summary>
        public static string ParameterNullExceptionMessageObjectIs {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageObjectIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} on method {1}..
        /// </summary>
        public static string ParameterNullExceptionMessageOnMethod {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMessageOnMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method expected a non-null, or non-default-value of the type {0}..
        /// </summary>
        public static string ParameterNullExceptionMethodExpectedNonNull {
            get {
                return ResourceManager.GetString("ParameterNullExceptionMethodExpectedNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No parameter name passed, however the following parameters were available at the time the exception was thrown:
        ///.
        /// </summary>
        public static string ParameterNullExceptionNoName {
            get {
                return ResourceManager.GetString("ParameterNullExceptionNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the failing parameter type, perhaps the name passed was incorrect? .
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermine {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unable to determine the method&apos;s declaring type..
        /// </summary>
        public static string ParameterNullExceptionUnableToDetermineDeclaringType {
            get {
                return ResourceManager.GetString("ParameterNullExceptionUnableToDetermineDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUSKF Policies and Procedures.
        /// </summary>
        public static string PoliciesProcedures {
            get {
                return ResourceManager.GetString("PoliciesProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject is requried..
        /// </summary>
        public static string SubjectIsRequried {
            get {
                return ResourceManager.GetString("SubjectIsRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine userid from given parameter.
        /// </summary>
        public static string UnableToDetermineId {
            get {
                return ResourceManager.GetString("UnableToDetermineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find news/event with the given id..
        /// </summary>
        public static string UnableToFindEvent {
            get {
                return ResourceManager.GetString("UnableToFindEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name not available.
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the id {0} could not be found.
        /// </summary>
        public static string UserWithIdNotFound {
            get {
                return ResourceManager.GetString("UserWithIdNotFound", resourceCulture);
            }
        }
    }
}
