// <auto-generated />
namespace AUSKF.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M1_011116 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M1_011116));
        
        string IMigrationMetadata.Id
        {
            get { return "201601120239140_M1_011116"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
